#!/usr/bin/env python3

import curses
from curses import wrapper, window
from curses.textpad import Textbox
from curses.panel import *

def split_win(screen_num, screens, windows):
        screens[screen_num].clear()
        win = None
        maxy0, maxx0 = windows[screen_num][0].getmaxyx()
        new_y_len = int(maxy0*len(windows[screen_num])/(len(windows[screen_num])+1))
        for idx,w in enumerate(windows[screen_num]):
               w.resize(new_y_len, maxx0)
               if idx > 0:
                       w.mvwin(int(w.getparyx()[0]-new_y_len*len(windows[screen_num])/(len(windows[screen_num])+1)), 0)
               y, x = w.getparyx()
               w.border()
               w.refresh()
        win = screens[screen_num].subwin(new_y_len, maxx0, y+new_y_len, 0)
        win.border()
        win.idcok(True)
        win.idlok(True)
        win.scrollok(True)
        windows[screen_num].append(win)
        screens[screen_num].refresh()
        return Textbox(win)

def create_screen(screen_num, screens, panels, cmdlines, cmds, windows):
        # setup screen
        screens[screen_num] = curses.initscr()
        panels[screen_num] = new_panel(screens[screen_num])
        panels[screen_num].top()
        update_panels()
        curses.doupdate()
        maxy, maxx = screens[screen_num].getmaxyx()

        # setup cmdline
        cmdlines[screen_num] = screens[screen_num].subwin(1, maxx, maxy-1, 0)
        cmdlines[screen_num].idcok(True)
        cmds[screen_num] = Textbox(cmdlines[screen_num])
        cmds[screen_num].stripspaces = True

        # setup window
        win = screens[screen_num].subwin(maxy-2, maxx, 0, 0)
        win.border()
        win.idcok(True)
        win.idlok(True)
        win.scrollok(True)
        windows[screen_num] = [win]

        # return text box for text_boxes, and immediate editing
        return Textbox(win)

def remove_screen(screen_num, screens, panels, cmdlines, cmds, windows, text_boxes):
        del text_boxes[screen_num]
        del windows[screen_num]
        del cmds[screen_num]
        del cmdlines[screen_num]
        del panels[screen_num]
        del screens[screen_num]
        screen_num = len(screens)-1
        panels[screen_num].top()
        update_panels()
        curses.doupdate()
        return screen_num


def remove_win(screen_num, screens, windows):
        screens[screen_num].clear()
        prev_len_win = len(windows[screen_num])
        del windows[screen_num][-1]
        len_win = len(windows[screen_num])
        for idx,w in enumerate(windows[screen_num]):
                y, x = w.getparyx()
                maxy,maxx = w.getmaxyx()
                new_maxy = int((maxy-y)*(prev_len_win/len_win))
                if idx > 0:
                        newypos = int(y*(prev_len_win/len_win))
                        w.mvwin(newypos, 0)
                w.resize(new_maxy, maxx)
                y, x = w.getparyx()
                w.border()
                w.refresh()
        screens[screen_num].refresh()
        return

def main(stdscr):
        # screen setup
        stdscr.clear()
        screens = {}
        panels = {}
        cmdlines = {}
        cmds = {}
        windows = {}
        text_boxes = {}

        screen_num = 0
        win_num = 0

        # inital text box
        text_boxes[screen_num] = [create_screen(screen_num, screens, panels, cmdlines, cmds, windows)]
        text_boxes[screen_num][win_num].edit() # Ctrl-g to exit the text_box


        # run the program
        cmds[screen_num].edit()
        c = cmds[screen_num].gather()
        while c != '':
                # new screen
                if c == 'n ':
                        screen_num = len(screens)
                        text_boxes[screen_num] = [create_screen(screen_num, screens, panels, cmdlines, cmds, windows)]
                        win_num = 0
                        text_boxes[screen_num][win_num].edit()
                elif c == 'nw ':
                        text_boxes[screen_num].append(split_win(screen_num, screens, windows))
                        win_num += 1
                        text_boxes[screen_num][win_num].edit()
                # remove screen
                elif c == 'r ':
                        if len(screens) > 1:
                                screen_num = remove_screen(screen_num, screens, panels, cmdlines, cmds, windows, text_boxes)
                                win_num = 0
                        text_boxes[screen_num][win_num].edit()
                elif c == 'rw ':
                        if len(windows[screen_num]) > 1:
                                remove_win(screen_num, screens, windows)
                                win_num = 0
                        text_boxes[screen_num][win_num].edit()
                # next screen
                elif c == 's ':
                        if screen_num < len(screens) - 1:
                                screen_num += 1
                                win_num = 0
                        else:
                                screen_num = 0
                                win_num = 0
                        panels[screen_num].top()
                        update_panels()
                        curses.doupdate()
                        text_boxes[screen_num][win_num].edit()
                # next window
                elif c == 'w ':
                        if win_num < len(windows[screen_num]) - 1:
                                win_num += 1
                        else:
                                win_num = 0
                        text_boxes[screen_num][win_num].edit()
                # get cmd
                cmdlines[screen_num].clear()
                cmds[screen_num].edit()
                c = cmds[screen_num].gather()

        # end program
        curses.endwin()
        return


if __name__ == '__main__':
        wrapper(main)
