#!/usr/bin/env python3

import curses
from curses import wrapper, window
from curses.textpad import Textbox
from curses.panel import *

def main(stdscr):
        stdscr.clear()
        screen = curses.initscr()
#        curses.echo()
        stdscr.refresh()

        win0 = screen.subwin(0,0)
        pane0 = new_panel(win0)
        win0.idcok(True)
        win0.idlok(True)
        win0.scrollok(True)

        box = Textbox(win0)
        box.edit() # Ctrl-G to save and exit

        curses.endwin()
        return


if __name__ == '__main__':
        wrapper(main)
